### PR TITLE
added buildspec-prod

### PR DESCRIPTION
**Pull request by perichin**

### CODE REVIEW

**Comment by guyandy** [comment]
Do you need a prod version of this file?

**Comment by perichin** [comment]
Well, we need the build command to be `build:prod`, so that we can distinguish the environments and accordingly use the staging vs. prod opt url

**Comment by guyandy** [comment]
i guess the only difference is the 'no-production' flag. Do you know what
that does? You can add env vars in the codebuild stage

**Comment by perichin** [comment]
Yes, the flag sets the `env.isProd` that is later used in `preact.config.js` to `false`. I did add the env vars in the build stage, and now that you mentioned it, maybe we can go with just the one buildspec file. I will look more into this.

**Pull request merged**
